### ISSUE TITLE
Task

### ISSUE THREAD

**Issue by JohnKhandygo** [ADsty/reverse#1]
**Общая формулировка**
Разработать программу с графическим интерфейсом, реализующую указанную в задании функциональность, на языках Java и/или Kotlin. При проектировании использовать объектно-ориентированный подход. Разработать автоматические тесты для отдельных частей программы. Написанный код держать в отдельном проекте или модуле в репозитории на GitHub.

**Реверси**
Реализовать игру Реверси для двух игроков за одним компьютером, с графическим интерфейсом. Реализовать все правила игры и проверить их работоспособность тестами. Правила [здесь](https://ru.wikipedia.org/wiki/Реверси).

**Comment by JohnKhandygo** [comment]
Окей. На тройку сгодится. Будете дальше добивать?

**Comment by ADsty** [comment]
Мм ну если я все правильно понял , то у меня в сумме за курсовую работу с этой тройкой будет (5+4+3)/3 = 4 , если конечно я все правильно понял, 4 меня вполне устраивает , но уже после сессии я это задание добью дабы просто попробовать себя в этом деле . Если же что-то как то не так понял то конечно добью

**Comment by ADsty** [comment]
Ну и наверное потом попробую компьютерного игрока ввести в игру , но уже после сессии

**Comment by JohnKhandygo** [comment]
Да, Вы все правильно поняли. Тогда закрываю, в таблице ставлю 3 за третье задание и 4 как оценку за курсовой проект в этом семестре.
